# Generated by Django 5.0.4 on 2024-05-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_positive',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='probability',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
    ]
